[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "modular-hack"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.8"

[dependencies]
modular = ">=25.5.0.dev2025062705,<26"
python = "3.11.*"
pytorch = ">=2.7.1,<3"
max = ">=25.5.0.dev2025062705,<26"

[pypi-dependencies]
fire = ">=0.7.0, <0.8"
sentencepiece = "*"
xformers = ">=0.0.31, <0.0.32"
tiktoken = "*"
blobfile = ">=3.0.0, <4"
flask = ">=3.1.1, <4"
einops = ">=0.8.1, <0.9"
transformers = "*"
